test:
	coverage run -m unittest discover tests
	coverage html

test_config_parser:
	python3 -m unittest tests.test_config_parser

test_data_filter:
	python3 -m unittest tests.test_data_filter

test_petro5_hdf5:
	python3 -m unittest tests.test_petro5_hdf5

test_h5_expand:
	python3 -m unittest tests.test_h5_expand