test:
	coverage run -m unittest discover tests
	coverage html

test_treat_por_file:
	python3 -m unittest tests.test_treat_porosity_file

test_filter_and_merge_seismic_por:
	python3 -m unittest tests.test_filter_and_merge_seismic_por
	